[tool.poetry]
name = "nuclear-analysis"
version = "0.1.0"
description = ""
authors = ["Abtin Salahshor <abtin.sr@gmail.com>"]

[tool.poetry.dependencies]
python = "^3.9"
pandas = "^2.0.3"
numpy = "^1.25.2"
seaborn = "^0.12.2"
scikit-learn = "^1.3.0"
sklearn = "^0.0.post7"
statsmodels = "^0.14.0"

[tool.poetry.dev-dependencies]
pytest = "^5.2"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
